config:
  default:
      features:
        new_analytics_refunds: "from deployment-values file -helm-sandbox-values.yaml"
        maintainence_alert: "from infra-values file -helm-sandbox-values.yaml"
