config:
  default:
      features:
        new_analytics_refunds: "from deployment-values file - deployment-configs/prod-values.yaml"
        maintainence_alert: "from deployment-values file - deployment-configs/prod-values.yaml"
