config:
  default:
      features:
        new_analytics_refunds: "from infra-values file - infra-configurations/prod-values.yaml"
        maintainence_alert: "from infra-values file - infra-configurations/prod-values.yaml"
